[package]
name = "cncli"
version = "0.1.0"
authors = ["Andrew Westberg <andrewwestberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9.1"
byteorder = "1.3.4"
hex = "0.3.1"
rusqlite = "0.24.1"
serde_cbor = "0.10.2"
structopt = "0.3.20"

# logging
log = "0.4.11"
env_logger = "0.8.1"
pretty_env_logger = "0.4.0"