[package]
name = "cncli"
version = "0.1.0"
authors = ["Andrew Westberg <andrewwestberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
hex = "0.3.1"
serde = "1.0.117"
serde_derive="1.0.117"
serde_cbor = "0.10.2"
structopt = "0.3.20"